/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import com.mycompany.casadoloresproject.CListas;
import entities.CAdministrador;
import entities.CBartender;
import entities.CCocinero;
import entities.CMesero;
import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class VCreateUser extends javax.swing.JFrame {

    /**
     * Creates new form VCreateUser
     */
    CListas listas = null;

    public VCreateUser(CListas listas) {
        initComponents();
        this.listas = listas;
        rbAdministrador.setSelected(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        rbAdministrador = new javax.swing.JRadioButton();
        tfPass = new javax.swing.JPasswordField();
        rbMesero = new javax.swing.JRadioButton();
        rbBarMan = new javax.swing.JRadioButton();
        btnCrear = new javax.swing.JButton();
        rbCocinero = new javax.swing.JRadioButton();
        btnCancelar = new javax.swing.JButton();
        tfName = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Nuevo Usuario");

        jLabel2.setText("Nombre:");

        jLabel3.setText("Contraseña:");

        buttonGroup1.add(rbAdministrador);
        rbAdministrador.setText("Administrador");

        buttonGroup1.add(rbMesero);
        rbMesero.setText("Mesero");

        buttonGroup1.add(rbBarMan);
        rbBarMan.setText("BarMan");

        btnCrear.setText("Crear");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbCocinero);
        rbCocinero.setText("Cocinero");

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rbCocinero)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(148, 148, 148))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(rbAdministrador)
                                    .addGap(107, 107, 107))
                                .addComponent(rbMesero, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(58, 58, 58)
                                    .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(rbBarMan))
                        .addGap(125, 159, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(178, 178, 178))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(141, 141, 141)
                    .addComponent(tfPass, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(153, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jLabel3)
                .addGap(42, 42, 42)
                .addComponent(rbAdministrador)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbMesero)
                .addGap(18, 18, 18)
                .addComponent(rbBarMan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rbCocinero)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCrear)
                    .addComponent(btnCancelar))
                .addGap(28, 28, 28))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(126, 126, 126)
                    .addComponent(tfPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(235, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        String name, pass;
        int ID = 0;

        name = tfName.getText();
        pass = tfPass.getText();

        if (rbAdministrador.isSelected()) {
            ID = (listas.administradorList.isEmpty()) ? 100 : listas.createIdAdministrador();
            listas.crearAdministrador(new CAdministrador(name, pass, ID));
        } else if (rbBarMan.isSelected()) {
            ID = (listas.bartenderList.isEmpty()) ? 200 : listas.createIdBartender();
            listas.crearBartender(new CBartender(name, pass, ID));
        } else if (rbMesero.isSelected()) {
            ID = (listas.meseroList.isEmpty()) ? 300 : listas.createIdMesero();
            System.out.println("" + ID);
            listas.crearMesero(new CMesero(name, pass, ID));
        } else if (rbCocinero.isSelected()) {
            ID = (listas.cocineroList.isEmpty()) ? 400 : listas.createIdCocinero();
            listas.crearCocinero(new CCocinero(name, pass, ID));
        }

        JOptionPane.showMessageDialog(this, "Tu ID es el: " + ID, "Usuario Creado", 1);

        clearForm();


    }//GEN-LAST:event_btnCrearActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        new vMenuAdministrador(listas).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    public void clearForm() {
        tfName.setText("");
        tfPass.setText("");
        rbAdministrador.setSelected(true);
    }
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCrear;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JRadioButton rbAdministrador;
    private javax.swing.JRadioButton rbBarMan;
    private javax.swing.JRadioButton rbCocinero;
    private javax.swing.JRadioButton rbMesero;
    private javax.swing.JTextField tfName;
    private javax.swing.JPasswordField tfPass;
    // End of variables declaration//GEN-END:variables
}
