/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import com.mycompany.casadoloresproject.CListas;
import entities.CBebida;
import entities.CPlatillo;

/**
 *
 * @author DELL
 */
public class VCreateProduct extends javax.swing.JFrame {

    /**
     * Creates new form VCreateProduct
     */
    CListas listas = null;
    public VCreateProduct(CListas listas) {
        initComponents();
        this.listas = listas;
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cbStock = new javax.swing.JCheckBox();
        cbHorario = new javax.swing.JComboBox<>();
        cbCategoria = new javax.swing.JComboBox<>();
        rbBibida = new javax.swing.JRadioButton();
        rbComida = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        btnCrear = new javax.swing.JButton();
        tfNombre = new javax.swing.JTextField();
        tfPrecio = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(215, 115, 17));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Nombre:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        jLabel7.setText("Tipo:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));

        jLabel3.setText("Categoria:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        jLabel4.setText("Precio:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, -1));

        jLabel6.setText("Horario:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(43, 279, -1, -1));

        jLabel5.setText("Stock:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 318, -1, -1));

        cbStock.setBackground(new java.awt.Color(215, 115, 17));
        jPanel1.add(cbStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 318, -1, -1));

        cbHorario.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mañana", "Tarde", "Todo el Dia" }));
        cbHorario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbHorarioActionPerformed(evt);
            }
        });
        jPanel1.add(cbHorario, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, -1, -1));

        cbCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Entrada", "Principal", "Postre", "Extras" }));
        jPanel1.add(cbCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, -1, -1));

        rbBibida.setBackground(new java.awt.Color(215, 115, 17));
        buttonGroup1.add(rbBibida);
        rbBibida.setForeground(new java.awt.Color(0, 0, 0));
        rbBibida.setText("Bebida");
        rbBibida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbBibidaActionPerformed(evt);
            }
        });
        jPanel1.add(rbBibida, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, -1, -1));

        rbComida.setBackground(new java.awt.Color(215, 115, 17));
        buttonGroup1.add(rbComida);
        rbComida.setSelected(true);
        rbComida.setText("Comida");
        rbComida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbComidaActionPerformed(evt);
            }
        });
        jPanel1.add(rbComida, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, -1, -1));

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Nuevo Producto");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, -1));

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 330, 88, -1));

        btnCrear.setText("Crear");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });
        jPanel1.add(btnCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, 86, -1));
        jPanel1.add(tfNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 210, -1));
        jPanel1.add(tfPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 93, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 370));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
       new vMenuAdministrador(listas).setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed
        String name, categoria, horario;
        int precio;
        boolean stock;
        
        name = tfNombre.getText();
        categoria = (String) cbCategoria.getSelectedItem();
        horario = (String) cbHorario.getSelectedItem();
        precio = Integer.parseInt(tfPrecio.getText());
        stock = cbStock.isSelected();

        if(rbBibida.isSelected()){
            listas.crearBebida(new CBebida(name, categoria, precio, horario, stock));
           listas.showBebidas();
        }else{
            listas.crearPlatillo(new CPlatillo(name, categoria, precio, horario, stock));
            listas.showPlatillo();
        }
        
        cleanForm();
    }//GEN-LAST:event_btnCrearActionPerformed

    private void cleanForm(){
        tfNombre.setText("");
        tfPrecio.setText("");
        rbComida.setSelected(true);
        cbCategoria.removeAllItems();
        cbCategoria.addItem("Entradas");
        cbCategoria.addItem("Principales");
        cbCategoria.addItem("Postres");
        cbCategoria.addItem("Extras");
        cbHorario.removeAllItems();
        cbHorario.addItem("Mañana");
        cbHorario.addItem("Tarde");
        cbHorario.addItem("Todo el Dia");
        cbStock.setSelected(false);
        
    }
    private void rbBibidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbBibidaActionPerformed
        // TODO add your handling code here:
        cbCategoria.removeAllItems();
        cbCategoria.addItem("Tequilas");
        cbCategoria.addItem("Naturales");
        cbCategoria.addItem("Refrescos");
        cbCategoria.addItem("Cafeteria");
    }//GEN-LAST:event_rbBibidaActionPerformed

    private void rbComidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbComidaActionPerformed
        // TODO add your handling code here:
        cbCategoria.removeAllItems();
        cbCategoria.addItem("Entradas");
        cbCategoria.addItem("Principales");
        cbCategoria.addItem("Postres");
        cbCategoria.addItem("Extras");
    }//GEN-LAST:event_rbComidaActionPerformed

    private void cbHorarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbHorarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbHorarioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCrear;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cbCategoria;
    private javax.swing.JComboBox<String> cbHorario;
    private javax.swing.JCheckBox cbStock;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton rbBibida;
    private javax.swing.JRadioButton rbComida;
    private javax.swing.JTextField tfNombre;
    private javax.swing.JTextField tfPrecio;
    // End of variables declaration//GEN-END:variables
}
