/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import com.mycompany.casadoloresproject.CListas;
import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class vMenuAdministrador extends javax.swing.JFrame {

    /**
     * Creates new form vMenuAdministrador
     */
    CListas listas = null;

    public vMenuAdministrador(CListas listas) {
        initComponents();
        this.listas = listas;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        miUserCrear = new javax.swing.JMenuItem();
        miUserBuscar = new javax.swing.JMenuItem();
        miUserEliminar = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        miProCrear = new javax.swing.JMenuItem();
        miProBuscar = new javax.swing.JMenuItem();
        miProEliminar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Usuarios");

        miUserCrear.setText("Crear");
        miUserCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miUserCrearActionPerformed(evt);
            }
        });
        jMenu1.add(miUserCrear);

        miUserBuscar.setText("Buscar");
        jMenu1.add(miUserBuscar);

        miUserEliminar.setText("Eliminar");
        miUserEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miUserEliminarActionPerformed(evt);
            }
        });
        jMenu1.add(miUserEliminar);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Productos");

        miProCrear.setText("Crear");
        miProCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miProCrearActionPerformed(evt);
            }
        });
        jMenu2.add(miProCrear);

        miProBuscar.setText("Buscar");
        jMenu2.add(miProBuscar);

        miProEliminar.setText("Eliminar");
        miProEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miProEliminarActionPerformed(evt);
            }
        });
        jMenu2.add(miProEliminar);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Crear Producto
    private void miUserCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miUserCrearActionPerformed
        // TODO add your handling code here:
        new VCreateUser(listas).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_miUserCrearActionPerformed

    private void miProCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miProCrearActionPerformed
        new VCreateProduct(listas).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_miProCrearActionPerformed

    private void miUserEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miUserEliminarActionPerformed
        // TODO add your handling code here:
        int bdID = 0;
        String ID = JOptionPane.showInputDialog("Ingresa el ID del Usuario");

        switch (ID.substring(0, 1)) {
            case "1" -> {
                bdID = listas.BuscarIdAdministrador(Integer.parseInt(ID));
                if(bdID == -1){
                    showMessageDialogFail(ID);
                }else{
                    listas.removeAdministrador(bdID);
                    showMessageDialogSuccess("Usuario");
                }
            }
            case "2" -> {
                bdID = listas.BuscarIdBartender(Integer.parseInt(ID));
                if(bdID == -1){
                    showMessageDialogFail(ID);
                }else{
                    listas.removeBartender(bdID);
                    showMessageDialogSuccess("Usuario");
                }
            }
            case "3" -> {
                bdID = listas.BuscarIdMesero(Integer.parseInt(ID));
                if(bdID == -1){
                    showMessageDialogFail(ID);
                }else{
                    listas.removeMesero(bdID);
                    showMessageDialogSuccess("Usuario");
                }
            }
            case "4" -> {
                bdID = listas.BuscarIdCocinero(Integer.parseInt(ID));
                if(bdID == -1){
                    showMessageDialogFail(ID);
                }else{
                    listas.removeCocinero(bdID);
                    showMessageDialogSuccess("Usuario");
                }
            }
            default -> {
            }
        }
    }//GEN-LAST:event_miUserEliminarActionPerformed

    private void miProEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miProEliminarActionPerformed
        // TODO add your handling code here:
        int bdID = 0;
        String name = JOptionPane.showInputDialog("Ingresa el Nombre del producto");
        
        int indexComida = listas.buscarComida(name);
        int indexBebida = listas.buscarBebida(name);
        
        if(indexComida == -1 && indexBebida == -1){
            JOptionPane.showMessageDialog(this, "No se encontró el Producto", "Eliminar Producto", 1);
            return;
        }
        
        if(indexComida != -1){
            listas.removePlatillo(indexComida);
            showMessageDialogSuccess("Comida");
            return;
        }
        
        listas.removeBebida(indexComida);
        showMessageDialogSuccess("Bebida");
    }//GEN-LAST:event_miProEliminarActionPerformed

    private void showMessageDialogSuccess(String item){
        JOptionPane.showMessageDialog(this, "Ha sido eliminado correctamente", "Eliminar " + item, 1);
    }
    
    private void showMessageDialogFail(String ID){
        JOptionPane.showMessageDialog(this, "No se encontró Usuario con el ID: " + ID, "Eliminar Usuario", 1);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem miProBuscar;
    private javax.swing.JMenuItem miProCrear;
    private javax.swing.JMenuItem miProEliminar;
    private javax.swing.JMenuItem miUserBuscar;
    private javax.swing.JMenuItem miUserCrear;
    private javax.swing.JMenuItem miUserEliminar;
    // End of variables declaration//GEN-END:variables
}
