/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import com.mycompany.casadoloresproject.CListas;
import entities.CMesero;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author marco
 */
public final class VMesasTerraza extends javax.swing.JFrame {

    /**
     * Creates new form VMapaMesas
     */
    
   CListas listas;
    CMesero mesero;
    int index;
    
    public VMesasTerraza(CListas listas, int index) {
      
        initComponents();
        this.setLocationRelativeTo(null);
        cargarImagenMesas();
        this.index = index;
        this.listas = listas;
        this.mesero = listas.meseroList.get(index);
        cargarEtiquetas();
        this.setLocationRelativeTo(null);
    }
    public void cargarImagenMesas(){
        
        ImageIcon imagenSubtraction1 = new ImageIcon("src/main/java/img/desk.png");
        Image imagen1 = imagenSubtraction1.getImage();
        Image imagenEscalada1 = imagen1.getScaledInstance(134, 134,java.awt.Image.SCALE_SMOOTH);
        imagenSubtraction1 = new ImageIcon(imagenEscalada1);
        btnMesa8.setIcon(imagenSubtraction1);
        
        ImageIcon imagenSubtraction2 = new ImageIcon("src/main/java/img/desk.png");
        Image imagen2 = imagenSubtraction2.getImage();
        Image imagenEscalada2 = imagen2.getScaledInstance(134, 134,java.awt.Image.SCALE_SMOOTH);
        imagenSubtraction2 = new ImageIcon(imagenEscalada2);
        btnMesa9.setIcon(imagenSubtraction2);
        
        ImageIcon imagenSubtraction3 = new ImageIcon("src/main/java/img/desk.png");
        Image imagen3 = imagenSubtraction3.getImage();
        Image imagenEscalada3 = imagen3.getScaledInstance(134, 134,java.awt.Image.SCALE_SMOOTH);
        imagenSubtraction3 = new ImageIcon(imagenEscalada3);
        btnMesa10.setIcon(imagenSubtraction3);
        
        ImageIcon imagenSubtraction4 = new ImageIcon("src/main/java/img/desk.png");
        Image imagen4 = imagenSubtraction4.getImage();
        Image imagenEscalada4 = imagen4.getScaledInstance(134, 134,java.awt.Image.SCALE_SMOOTH);
        imagenSubtraction4 = new ImageIcon(imagenEscalada4);
        btnMesa11.setIcon(imagenSubtraction4);
        
    }
    
    public void cargarEtiquetas(){
        labelNombre.setText(mesero.getsUsername());
        labelID.setText(String.valueOf(mesero.getiID()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lbNombre = new javax.swing.JLabel();
        labelNombre = new javax.swing.JLabel();
        lbID = new javax.swing.JLabel();
        labelID = new javax.swing.JLabel();
        lbArea = new javax.swing.JLabel();
        cbMapa = new javax.swing.JComboBox<>();
        lbMesa8 = new javax.swing.JLabel();
        lbMesa9 = new javax.swing.JLabel();
        lbMesa10 = new javax.swing.JLabel();
        lbMesa11 = new javax.swing.JLabel();
        btnMesa8 = new javax.swing.JButton();
        btnMesa9 = new javax.swing.JButton();
        btnMesa10 = new javax.swing.JButton();
        btnMesa11 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setBackground(new java.awt.Color(255, 153, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 102, 0));

        lbNombre.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        lbNombre.setText("Nombre");

        labelNombre.setText("nombre");

        lbID.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        lbID.setText("Id");

        labelID.setText("id");

        lbArea.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        lbArea.setText("Area");

        cbMapa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Terraza", "Comedor" }));
        cbMapa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMapaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(64, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cbMapa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelID)
                            .addComponent(lbID))
                        .addGap(41, 41, 41)))
                .addGap(70, 70, 70))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(lbArea))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelNombre)
                            .addComponent(lbNombre))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(lbNombre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelNombre)
                .addGap(51, 51, 51)
                .addComponent(lbID)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelID)
                .addGap(80, 80, 80)
                .addComponent(lbArea)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbMapa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(559, 0, -1, 491));

        lbMesa8.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        lbMesa8.setText("8");
        jPanel1.add(lbMesa8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, -1, -1));

        lbMesa9.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        lbMesa9.setText("9");
        jPanel1.add(lbMesa9, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 180, 10, -1));

        lbMesa10.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        lbMesa10.setText("10");
        jPanel1.add(lbMesa10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, 20, -1));

        lbMesa11.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        lbMesa11.setText("11");
        jPanel1.add(lbMesa11, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 300, 20, -1));

        btnMesa8.setBackground(new java.awt.Color(204, 204, 204));
        btnMesa8.setBorderPainted(false);
        btnMesa8.setContentAreaFilled(false);
        btnMesa8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMesa8ActionPerformed(evt);
            }
        });
        jPanel1.add(btnMesa8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 126, 95));

        btnMesa9.setBackground(new java.awt.Color(204, 204, 204));
        btnMesa9.setBorderPainted(false);
        btnMesa9.setContentAreaFilled(false);
        jPanel1.add(btnMesa9, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 140, 126, 95));

        btnMesa10.setBackground(new java.awt.Color(204, 204, 204));
        btnMesa10.setBorderPainted(false);
        btnMesa10.setContentAreaFilled(false);
        jPanel1.add(btnMesa10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 126, 95));

        btnMesa11.setBackground(new java.awt.Color(204, 204, 204));
        btnMesa11.setBorderPainted(false);
        btnMesa11.setContentAreaFilled(false);
        btnMesa11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMesa11ActionPerformed(evt);
            }
        });
        jPanel1.add(btnMesa11, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 260, 126, 95));

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMesa8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMesa8ActionPerformed
        JOptionPane.showMessageDialog(null, "Hola Rangel");
    }//GEN-LAST:event_btnMesa8ActionPerformed

    private void btnMesa11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMesa11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMesa11ActionPerformed

    private void cbMapaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMapaActionPerformed
        
        if(cbMapa.getSelectedItem().equals("Comedor")){
            new VMesasComedor(listas, index).setVisible(true); 
            this.dispose();
        }
    }//GEN-LAST:event_cbMapaActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMesa10;
    private javax.swing.JButton btnMesa11;
    private javax.swing.JButton btnMesa8;
    private javax.swing.JButton btnMesa9;
    private javax.swing.JComboBox<String> cbMapa;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labelID;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel lbArea;
    private javax.swing.JLabel lbID;
    private javax.swing.JLabel lbMesa10;
    private javax.swing.JLabel lbMesa11;
    private javax.swing.JLabel lbMesa8;
    private javax.swing.JLabel lbMesa9;
    private javax.swing.JLabel lbNombre;
    // End of variables declaration//GEN-END:variables
}
