/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views.mesero;

import com.mycompany.casadoloresproject.CListas;
import entities.CComanda;
import entities.CMesero;
import java.awt.Image;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author marco
 */
public final class VMesasTerraza extends javax.swing.JInternalFrame {

    /**
     * Creates new form VMapaMesas
     */
    CListas listas;
    CMesero mesero;
    int index;
    VMenuMesero menu;

    public VMesasTerraza(CListas listas, int index, VMenuMesero menu) {

        initComponents();
        this.listas = listas;
        mesero = listas.meseroList.get(index);
        cargarImagenMesas();
        this.index = index;
        this.menu = menu;

        enableTables();
    }

    public void cargarImagenMesas() {

        ImageIcon imagenSubtraction1 = new ImageIcon("src/main/java/img/desk.png");
        Image imagen1 = imagenSubtraction1.getImage();
        Image imagenEscalada1 = imagen1.getScaledInstance(134, 134, java.awt.Image.SCALE_SMOOTH);
        imagenSubtraction1 = new ImageIcon(imagenEscalada1);
        btnMesa8.setIcon(imagenSubtraction1);

        ImageIcon imagenSubtraction2 = new ImageIcon("src/main/java/img/desk.png");
        Image imagen2 = imagenSubtraction2.getImage();
        Image imagenEscalada2 = imagen2.getScaledInstance(134, 134, java.awt.Image.SCALE_SMOOTH);
        imagenSubtraction2 = new ImageIcon(imagenEscalada2);
        btnMesa9.setIcon(imagenSubtraction2);

        ImageIcon imagenSubtraction3 = new ImageIcon("src/main/java/img/desk.png");
        Image imagen3 = imagenSubtraction3.getImage();
        Image imagenEscalada3 = imagen3.getScaledInstance(134, 134, java.awt.Image.SCALE_SMOOTH);
        imagenSubtraction3 = new ImageIcon(imagenEscalada3);
        btnMesa10.setIcon(imagenSubtraction3);

        ImageIcon imagenSubtraction4 = new ImageIcon("src/main/java/img/desk.png");
        Image imagen4 = imagenSubtraction4.getImage();
        Image imagenEscalada4 = imagen4.getScaledInstance(134, 134, java.awt.Image.SCALE_SMOOTH);
        imagenSubtraction4 = new ImageIcon(imagenEscalada4);
        btnMesa11.setIcon(imagenSubtraction4);

    }

    private void enableTables() {
        for (CMesero meseroLocal : listas.meseroList) {
            if (meseroLocal.getiID() != mesero.getiID()) {
                for (CComanda comanda : meseroLocal.getComandas()) {
                    switch (comanda.getMesaID()) {
                        case 8: {
                            btnMesa8.setVisible(false);
                            btnMesa8.setEnabled(false);
                            break;
                        }
                        case 9: {
                            btnMesa9.setVisible(false);
                            btnMesa9.setEnabled(false);
                            break;
                        }
                        case 10: {
                            btnMesa10.setVisible(false);
                            btnMesa10.setEnabled(false);
                            break;
                        }
                        case 11: {
                            btnMesa11.setVisible(false);
                            btnMesa11.setEnabled(false);
                            break;
                        }
                    }
                }
            }

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbMesa8 = new javax.swing.JLabel();
        lbMesa9 = new javax.swing.JLabel();
        lbMesa10 = new javax.swing.JLabel();
        lbMesa11 = new javax.swing.JLabel();
        btnMesa8 = new javax.swing.JButton();
        btnMesa9 = new javax.swing.JButton();
        btnMesa10 = new javax.swing.JButton();
        btnMesa11 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 153, 51));
        jPanel1.setPreferredSize(new java.awt.Dimension(910, 570));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbMesa8.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        lbMesa8.setText("8");
        jPanel1.add(lbMesa8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, -1, -1));

        lbMesa9.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        lbMesa9.setText("9");
        jPanel1.add(lbMesa9, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 180, 10, -1));

        lbMesa10.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        lbMesa10.setText("10");
        jPanel1.add(lbMesa10, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, 20, -1));

        lbMesa11.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        lbMesa11.setText("11");
        jPanel1.add(lbMesa11, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 300, 20, -1));

        btnMesa8.setBackground(new java.awt.Color(204, 204, 204));
        btnMesa8.setBorderPainted(false);
        btnMesa8.setContentAreaFilled(false);
        btnMesa8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMesa8ActionPerformed(evt);
            }
        });
        jPanel1.add(btnMesa8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 126, 95));

        btnMesa9.setBackground(new java.awt.Color(204, 204, 204));
        btnMesa9.setBorderPainted(false);
        btnMesa9.setContentAreaFilled(false);
        btnMesa9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMesa9ActionPerformed(evt);
            }
        });
        jPanel1.add(btnMesa9, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 140, 126, 95));

        btnMesa10.setBackground(new java.awt.Color(204, 204, 204));
        btnMesa10.setBorderPainted(false);
        btnMesa10.setContentAreaFilled(false);
        btnMesa10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMesa10ActionPerformed(evt);
            }
        });
        jPanel1.add(btnMesa10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 126, 95));

        btnMesa11.setBackground(new java.awt.Color(204, 204, 204));
        btnMesa11.setBorderPainted(false);
        btnMesa11.setContentAreaFilled(false);
        btnMesa11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMesa11ActionPerformed(evt);
            }
        });
        jPanel1.add(btnMesa11, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 260, 126, 95));

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jLabel1.setText("Area Terraza");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 40, 410, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 921, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 592, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMesa8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMesa8ActionPerformed
        createComanda(8);
    }//GEN-LAST:event_btnMesa8ActionPerformed

    private void btnMesa11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMesa11ActionPerformed
        // TODO add your handling code here:
        createComanda(11);
    }//GEN-LAST:event_btnMesa11ActionPerformed

    private void btnMesa9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMesa9ActionPerformed
        // TODO add your handling code here:
        createComanda(9);
    }//GEN-LAST:event_btnMesa9ActionPerformed

    private void btnMesa10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMesa10ActionPerformed
        // TODO add your handling code here:
        createComanda(10);
    }//GEN-LAST:event_btnMesa10ActionPerformed
    
    private void createComanda(int mesaID) {
        boolean isActive = listas.isTableActive(mesero, mesaID);
        if (!isActive) {
            DateFormat dateFormat = new SimpleDateFormat("HH:mm");
            Date date = new Date();
            mesero.setComanda(new CComanda(dateFormat.format(date), mesaID));
        }
        new VMenuCreateComanda(listas, index, mesaID).setVisible(true);
        menu.dispose();
    }
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMesa10;
    private javax.swing.JButton btnMesa11;
    private javax.swing.JButton btnMesa8;
    private javax.swing.JButton btnMesa9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbMesa10;
    private javax.swing.JLabel lbMesa11;
    private javax.swing.JLabel lbMesa8;
    private javax.swing.JLabel lbMesa9;
    // End of variables declaration//GEN-END:variables
}
